---
title: "Coiba POI Map"
author: "Brendan Barrett"
date: "6/28/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(mapview)
library(rgdal)
library(sf)
library(raster)
```


```{r map data readin , echo=FALSE , verbose=FALSE , message=FALSE}

##### load camera traps
cam_ids <- read.csv(file="map/coiba_camtrap_ids_gps.csv") #generated with this script file https://github.com/bjbarrett/camtrap_coiba/blob/main/coiba_camtrap_gps_visualization.R
all_cams <- st_as_sf(cam_ids , coords = c("longitude", "latitude"), crs = 4326) #do it again if rading csv
all_cams_map <- mapview(all_cams , col.regions="gold"  )

filelist <- list.files(path="map/gpx/bjb_raw_garmin_folders" , full.names=TRUE)


##### load stream gps points
#####here is how we turn streams to lines and trim

#quebrada catarata

s1 <- readOGR(dsn ="map/gpx/bjb_raw_garmin_folders/Track_CAARATA QUEB2353.gpx" , layer="track_points")
s2 <- s1[3:6,]
coord<-as.data.frame(coordinates(s2))
queb_cat <- Line(as.data.frame(coordinates(s2)))
queb_cat <-Lines(list(queb_cat),ID="queb_catarata")

###discovery/watersource
s1 <- readOGR(dsn ="map/gpx/bjb_raw_garmin_folders/Track_DISCO QUEB 121828.gpx" , layer="track_points")
coord<-as.data.frame(coordinates(s1))
queb_watersource <- Line(as.data.frame(coordinates(s1)))
queb_watersource <-Lines(list(queb_watersource),ID="queb_watersource")

###bbc/alicia
s1 <- readOGR(dsn ="map/gpx/bjb_raw_garmin_folders/Track_QUEB BBC28 145539.gpx", layer="track_points")
s2 <- s1[4:108,]
coord<-as.data.frame(coordinates(s2))
queb_alicia <- Line(as.data.frame(coordinates(s2)))
queb_alicia <-Lines(list(queb_alicia),ID="queb_alicia")

###posa
s1 <- readOGR(dsn ="map/gpx/bjb_raw_garmin_folders/Track_QUEB POSA8 135357.gpx" , layer="track_points")
s2 <- s1[4:30,]
coord<-as.data.frame(coordinates(s2))
queb_posa <- Line(as.data.frame(coordinates(s2)))
queb_posa <-Lines(list(queb_posa),ID="queb_posa")
streams <- SpatialLines(list(queb_cat,queb_watersource,queb_alicia,queb_posa) , proj4string = s2@proj4string )
all_streams_map <- mapview(streams, color="blue" , lw=3)

#####lets add in tool sites
tools_w201707201901 <- readOGR(dsn = "map/gpx/cleaned/Tool Use Sites July 2017 Jan 2018.GPX", layer="waypoints")
tools_w201803 <- readOGR(dsn = "map/gpx/cleaned/Tool Use Sites Mar 2018.GPX", layer="waypoints")
tools_w201807 <- readOGR(dsn = "map/gpx/cleaned/Tool Use Site July 2018.GPX", layer="waypoints")
tools_w201901 <- readOGR(dsn = "map/gpx/cleaned/Tool Use Sites Jan 2019.GPX", layer="waypoints")
tools_w201903 <- readOGR(dsn = "map/gpx/cleaned/Tool Sites Mar 2019.GPX", layer="waypoints")

all_tools_map <- mapview(tools_w201707201901 , col.region="red" , cex=3) + mapview(tools_w201803 , col.region="orange" , cex=3) + mapview(tools_w201807 , col.region="yellow" , cex=3) + mapview(tools_w201901 , col.region="violet" , cex=3) + mapview(tools_w201903 , col.region="blue" , cex=3)

#all_tools_map + all_streams_map + all_cams_map


### add in almendras
#note, i did not get to finish punta ursula with camera trapsl
almendras <- readOGR(dsn = "map/gpx/cleaned/T_catappa_points.GPX", layer="waypoints")

most_almendras_map <- mapview(almendras , col.regions="green" , alpha.regions = 0.2 , cex=1.2)

all_tools_map + all_streams_map + all_cams_map + most_almendras_map #map of all trees, tools, cameras etc

#all_tools_map + all_streams_map +  most_almendras_map #map of all trees, tools, camerasm etc

```

```{r map grid , echo=FALSE , verbose=FALSE , message=FALSE}

## map with grid
grid_shapes <- rbind(tools_w201707201901,tools_w201803,tools_w201807) # define grid area using a subset of tools w/ same number columns

e <- as(raster::extent(min(grid_shapes@coords[,1]), max(grid_shapes@coords[,1]), min(grid_shapes@coords[,2]), max(grid_shapes@coords[,2])), "SpatialPolygons")
proj4string(e) <- crs(grid_shapes)
e3 <- spTransform(e, CRS("+init=EPSG:32616"))
ebuf <- buffer(e3, width = 1500) #add 500 m buffer
e2 <- st_as_sf(e)
e2b <- st_as_sf(ebuf)
grid_250m <- st_make_grid(e2b, square = T, cellsize = c(250, 250)) %>% # the grid, covering bounding box
  st_sf() # not really required, but makes the grid nicer to work with later

grid <- SpatialGrid(GridTopology(c(0, 0), c(1, 1), c(5, 4)))

# get coordinates of center coordinates of each cell
#above uses sp, so we can convert an sf to an sp object
grid_cams <- sf:::as_Spatial(grid_250m) #convert to
grid_ctr <- sp:::coordinates(grid_cams)

# plot over topo map
grid_centers <- as.data.frame(grid_ctr)
grid_centers$name <- paste("ZG", 1:nrow(grid_centers), sep = "_") # label per waypoint, needs to be called "name" to show up in GPX file
grid_centers_map <- st_as_sf(grid_centers, coords = c("V1", "V2"), crs = "+init=EPSG:32616")

# add tracks
#bind in raster package can deal with combining
#2018.03.28
trk_20180328<- readOGR(dsn =filelist[2] , layer="tracks")
#2017.03.24 bjb and claudio initial cross
trk_20170324  <- readOGR(dsn =filelist[7] , layer="tracks")
#2017.07.29 BJB PC cross
trk_20170729  <- readOGR(dsn =filelist[8] , layer="tracks")
#2017.12.20 cmm cross
trk_20171220   <- readOGR(dsn =filelist[9] , layer="tracks")

mccir_tr <- readOGR(dsn ="map/gpx/gps_dumps/MCCinreachJan2020.GPX" , layer="tracks")##inreaches need a space on xml code in first line removed to code
all_tracks <- bind(mccir_tr ,trk_20180328 ,trk_20170324,trk_20170729 ,trk_20171220)

mapview(grid_centers_map , cex=1.5 , label=TRUE , col.regions ="black") + mapview(grid_cams , alpha.regions=0.01) + all_cams_map + all_streams_map + all_tools_map + mapview(all_tracks)
```
